### ISSUE TITLE
Exception thrown: 'Leadtools.RasterException' in Leadtools.Annotations.Automation.dll

### ISSUE THREAD

**Issue by Popuri92** [codingbandit/ImageOCRWordConversion#1]
Hi,

While I am trying to run the application to open a document to be loaded in the DocumentViewer like you mentioned in your article which was published in CODE Project.com ,i am getting the error like "Document Capability is required" , in the output window its showing like "Exception thrown: 'Leadtools.RasterException' in Leadtools.Annotations.Automation.dll" can you please help me with that one.

Thanks !!

**Comment by codingbandit** [comment]
Hi Popuri92, this error indicates a problem with the license. Ensure you do he proper steps to load the license.
